### ISSUE TITLE
[BUG] Terminal opens up when booting one of the games.

### ISSUE THREAD

**Issue by DaBanana64** [stephini/SMAS_Launcher#13]
## Description
When booting up one of the games, the terminal boots up for no reason.

## Steps to Reproduce (for bugs)

Open the launcher, select one of the games, both game and terminal boots up.

## Expected Behavior

Only the game should boot up when selecting either of the games.

## Actual Behavior (for bugs)

The terminal boots up with the games.

## Settings Files (for bugs)

Default settings.

## Screenshots

How it should be when booting up: 
![image](https://github.com/stephini/SMAS_Launcher/assets/82652849/318b4126-b9de-44b0-b543-4789bebf988e)

How it does: 
![image](https://github.com/stephini/SMAS_Launcher/assets/82652849/95152cdc-45b2-45c1-8791-5c130a3981c6)

**Comment by stephini** [comment]
I am pleased to announce that the reported bug has been successfully addressed and resolved. Through careful investigation and iterative testing, I have implemented a workaround that effectively hides the terminal window during the game launch process. While this solution enhances the user experience by eliminating the visible terminal window, it is important to note that it does not address the underlying design limitation which necessitated the use of the terminal window. As such, it is considered a temporary workaround rather than a direct solution to the root cause of the issue. I will continue to monitor and assess opportunities for further improvements in future iterations.
